language: php

php:
   - 5.3
   - 5.4
   - 5.5
   - hhvm

matrix:
   allow_failures:
      - php: hhvm

before_script:
   - composer self-update
   - composer update --prefer-dist --no-interaction

script:
   - phpunit -c phpunit.xml.dist --coverage-text

notifications:
   email:
      - php@h4cc.de
