language: php

php:
   - 5.3
   - 5.4
   - 5.5
   - hhvm

matrix:
   allow_failures:
      - php: hhvm

before_script:
   - composer self-update
   - composer update --prefer-dist --no-interaction

script:
   - phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover
   - wget https://scrutinizer-ci.com/ocular.phar
   - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
   email:
      - php@h4cc.de
